"""add year columns

Revision ID: 16718741a572
Revises: 
Create Date: 2025-04-30 16:22:53.486292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '16718741a572'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aerich')
    op.add_column('bottom', sa.Column('year', sa.Integer(), nullable=True, comment='年份'))
    op.add_column('center_top_bottom', sa.Column('year', sa.Integer(), nullable=True, comment='年份'))
    op.add_column('center_top_top', sa.Column('year', sa.Integer(), nullable=True, comment='年份'))
    op.add_column('left_middle', sa.Column('year', sa.Integer(), nullable=True, comment='年份'))
    op.add_column('left_top', sa.Column('year', sa.Integer(), nullable=True, comment='年份'))
    op.add_column('right_middle', sa.Column('year', sa.Integer(), nullable=True, comment='年份'))
    op.add_column('right_top', sa.Column('year', sa.Integer(), nullable=True, comment='年份'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('right_top', 'year')
    op.drop_column('right_middle', 'year')
    op.drop_column('left_top', 'year')
    op.drop_column('left_middle', 'year')
    op.drop_column('center_top_top', 'year')
    op.drop_column('center_top_bottom', 'year')
    op.drop_column('bottom', 'year')
    op.create_table('aerich',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('version', sa.VARCHAR(length=255), nullable=False),
    sa.Column('app', sa.VARCHAR(length=100), nullable=False),
    sa.Column('content', sqlite.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
