"""add system fault log table

Revision ID: 4d7f51ba90ea
Revises: f6e5d4c3b2a1
Create Date: 2025-09-09 14:50:29.446926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d7f51ba90ea'
down_revision: Union[str, None] = 'f6e5d4c3b2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fault_data_id'), table_name='fault_data')
    op.drop_table('fault_data')
    op.drop_table('fault_analysis')
    op.drop_table('fault_trend')
    op.drop_table('fault_statistics')
    op.drop_index(op.f('ix_fault_record_cause_category'), table_name='fault_record')
    op.drop_index(op.f('ix_fault_record_fault_date'), table_name='fault_record')
    op.drop_index(op.f('ix_fault_record_fault_duration_hours'), table_name='fault_record')
    op.drop_index(op.f('ix_fault_record_notification_level'), table_name='fault_record')
    op.drop_index(op.f('ix_fault_record_province_fault_type'), table_name='fault_record')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_fault_record_province_fault_type'), 'fault_record', ['province_fault_type'], unique=False)
    op.create_index(op.f('ix_fault_record_notification_level'), 'fault_record', ['notification_level'], unique=False)
    op.create_index(op.f('ix_fault_record_fault_duration_hours'), 'fault_record', ['fault_duration_hours'], unique=False)
    op.create_index(op.f('ix_fault_record_fault_date'), 'fault_record', ['fault_date'], unique=False)
    op.create_index(op.f('ix_fault_record_cause_category'), 'fault_record', ['cause_category'], unique=False)
    op.create_table('fault_statistics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('stat_type', sa.VARCHAR(length=32), nullable=True),
    sa.Column('stat_date', sa.VARCHAR(length=32), nullable=True),
    sa.Column('city', sa.VARCHAR(length=64), nullable=True),
    sa.Column('profession', sa.VARCHAR(length=64), nullable=True),
    sa.Column('total_faults', sa.INTEGER(), nullable=True),
    sa.Column('major_faults', sa.INTEGER(), nullable=True),
    sa.Column('repeated_faults', sa.INTEGER(), nullable=True),
    sa.Column('preventable_faults', sa.INTEGER(), nullable=True),
    sa.Column('level_1_faults', sa.INTEGER(), nullable=True),
    sa.Column('level_2_faults', sa.INTEGER(), nullable=True),
    sa.Column('level_3_faults', sa.INTEGER(), nullable=True),
    sa.Column('level_4_faults', sa.INTEGER(), nullable=True),
    sa.Column('total_affected_users', sa.INTEGER(), nullable=True),
    sa.Column('total_impact_duration', sa.FLOAT(), nullable=True),
    sa.Column('avg_impact_duration', sa.FLOAT(), nullable=True),
    sa.Column('avg_response_time', sa.FLOAT(), nullable=True),
    sa.Column('avg_recovery_time', sa.FLOAT(), nullable=True),
    sa.Column('on_time_completion_rate', sa.FLOAT(), nullable=True),
    sa.Column('customer_satisfaction_rate', sa.FLOAT(), nullable=True),
    sa.Column('first_time_fix_rate', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fault_trend',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trend_date', sa.VARCHAR(length=32), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('month', sa.VARCHAR(length=16), nullable=True),
    sa.Column('city', sa.VARCHAR(length=64), nullable=True),
    sa.Column('region', sa.VARCHAR(length=64), nullable=True),
    sa.Column('profession', sa.VARCHAR(length=64), nullable=True),
    sa.Column('fault_count', sa.INTEGER(), nullable=True),
    sa.Column('fault_rate', sa.FLOAT(), nullable=True),
    sa.Column('mttr', sa.FLOAT(), nullable=True),
    sa.Column('mtbf', sa.FLOAT(), nullable=True),
    sa.Column('availability', sa.FLOAT(), nullable=True),
    sa.Column('month_on_month', sa.FLOAT(), nullable=True),
    sa.Column('year_on_year', sa.FLOAT(), nullable=True),
    sa.Column('predicted_value', sa.FLOAT(), nullable=True),
    sa.Column('confidence_interval', sa.VARCHAR(length=32), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fault_analysis',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fault_date', sa.VARCHAR(length=32), nullable=True),
    sa.Column('city', sa.VARCHAR(length=64), nullable=True),
    sa.Column('profession', sa.VARCHAR(length=64), nullable=True),
    sa.Column('fault_type', sa.VARCHAR(length=128), nullable=True),
    sa.Column('fault_level', sa.VARCHAR(length=32), nullable=True),
    sa.Column('fault_phenomenon', sa.TEXT(), nullable=True),
    sa.Column('impact_scope', sa.TEXT(), nullable=True),
    sa.Column('fault_cause', sa.TEXT(), nullable=True),
    sa.Column('fault_location', sa.VARCHAR(length=255), nullable=True),
    sa.Column('equipment_info', sa.TEXT(), nullable=True),
    sa.Column('occurrence_time', sa.VARCHAR(length=32), nullable=True),
    sa.Column('discovery_time', sa.VARCHAR(length=32), nullable=True),
    sa.Column('report_time', sa.VARCHAR(length=32), nullable=True),
    sa.Column('start_handle_time', sa.VARCHAR(length=32), nullable=True),
    sa.Column('recovery_time', sa.VARCHAR(length=32), nullable=True),
    sa.Column('complete_time', sa.VARCHAR(length=32), nullable=True),
    sa.Column('affected_users', sa.INTEGER(), nullable=True),
    sa.Column('impact_duration', sa.FLOAT(), nullable=True),
    sa.Column('service_interruption', sa.VARCHAR(length=128), nullable=True),
    sa.Column('handling_measures', sa.TEXT(), nullable=True),
    sa.Column('responsible_person', sa.VARCHAR(length=64), nullable=True),
    sa.Column('handling_department', sa.VARCHAR(length=128), nullable=True),
    sa.Column('emergency_response', sa.TEXT(), nullable=True),
    sa.Column('root_cause_analysis', sa.TEXT(), nullable=True),
    sa.Column('improvement_measures', sa.TEXT(), nullable=True),
    sa.Column('prevention_plan', sa.TEXT(), nullable=True),
    sa.Column('lesson_learned', sa.TEXT(), nullable=True),
    sa.Column('response_timeliness', sa.VARCHAR(length=32), nullable=True),
    sa.Column('handling_effectiveness', sa.VARCHAR(length=32), nullable=True),
    sa.Column('communication_quality', sa.VARCHAR(length=32), nullable=True),
    sa.Column('customer_satisfaction', sa.VARCHAR(length=32), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('month', sa.VARCHAR(length=16), nullable=True),
    sa.Column('quarter', sa.VARCHAR(length=16), nullable=True),
    sa.Column('week', sa.VARCHAR(length=16), nullable=True),
    sa.Column('is_major_fault', sa.INTEGER(), nullable=True),
    sa.Column('is_repeated_fault', sa.INTEGER(), nullable=True),
    sa.Column('is_preventable', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), nullable=True),
    sa.Column('remarks', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fault_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fault_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('fault_level', sa.VARCHAR(length=50), nullable=False),
    sa.Column('location', sa.VARCHAR(length=200), nullable=False),
    sa.Column('start_time', sa.DATETIME(), nullable=False),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.Column('duration', sa.FLOAT(), nullable=True),
    sa.Column('impact_scope', sa.VARCHAR(length=500), nullable=True),
    sa.Column('root_cause', sa.TEXT(), nullable=True),
    sa.Column('solution', sa.TEXT(), nullable=True),
    sa.Column('responsible_person', sa.VARCHAR(length=100), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fault_data_id'), 'fault_data', ['id'], unique=False)
    # ### end Alembic commands ###
