"""add huijugugan table

Revision ID: 50ba91c768b5
Revises: 16718741a572
Create Date: 2025-05-12 15:46:13.713503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ba91c768b5'
down_revision: Union[str, None] = '16718741a572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bi_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bi_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=32), nullable=True),
    sa.Column('month', sa.VARCHAR(length=16), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('baseline', sa.FLOAT(), nullable=True),
    sa.Column('challenge', sa.FLOAT(), nullable=True),
    sa.Column('indicator', sa.FLOAT(), nullable=True),
    sa.Column('battery_voltage_ratio', sa.FLOAT(), nullable=True),
    sa.Column('mains_load_ratio', sa.FLOAT(), nullable=True),
    sa.Column('ups_load_ratio', sa.FLOAT(), nullable=True),
    sa.Column('env_signal_ratio', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
