"""Add PUE drill down data table

Revision ID: add_pue_drill_down
Revises: 
Create Date: 2025-07-28 17:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision = 'add_pue_drill_down'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pue_drill_down_data',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('location', sa.String(length=255), nullable=True, comment='地点/机房'),
        sa.Column('month', sa.String(length=50), nullable=True, comment='月份'),
        sa.Column('year', sa.String(length=50), nullable=True, comment='年份'),
        sa.Column('work_type', sa.String(length=100), nullable=True, comment='作业形式'),
        sa.Column('work_category', sa.String(length=100), nullable=True, comment='作业分类'),
        sa.Column('sequence_no', sa.Integer(), nullable=True, comment='序号'),
        sa.Column('work_object', sa.String(length=255), nullable=True, comment='作业对象'),
        sa.Column('check_item', sa.Text(), nullable=True, comment='检查项'),
        sa.Column('operation_method', sa.Text(), nullable=True, comment='操作方法及建议值'),
        sa.Column('benchmark_value', sa.Text(), nullable=True, comment='标杆值'),
        sa.Column('execution_standard', sa.Text(), nullable=True, comment='执行标准'),
        sa.Column('execution_status', sa.Text(), nullable=True, comment='执行情况'),
        sa.Column('detailed_situation', sa.Text(), nullable=True, comment='详细情况'),
        sa.Column('quantification_standard', sa.String(length=100), nullable=True, comment='量化标准'),
        sa.Column('last_month_standard', sa.String(length=100), nullable=True, comment='上月量化标准'),
        sa.Column('quantification_unit', sa.String(length=50), nullable=True, comment='量化单位'),
        sa.Column('executor', sa.String(length=100), nullable=True, comment='执行人'),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pue_drill_down_data')
    # ### end Alembic commands ###
