"""add performance target and record models

Revision ID: e417db4c3d99
Revises: 4d7f51ba90ea
Create Date: 2025-09-10 16:07:08.457068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e417db4c3d99'
down_revision: Union[str, None] = '4d7f51ba90ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True, comment='关联的PerformanceTarget记录ID'),
    sa.Column('record_date', sa.DateTime(), nullable=True, comment='记录日期'),
    sa.Column('actual_value', sa.Float(), nullable=True, comment='实际值'),
    sa.Column('target_value', sa.Float(), nullable=True, comment='当期目标值'),
    sa.Column('achievement_rate', sa.Float(), nullable=True, comment='达成率（百分比）'),
    sa.Column('performance_level', sa.String(length=20), nullable=True, comment='绩效等级: excellent, good, acceptable, poor, critical'),
    sa.Column('is_target_met', sa.String(length=10), nullable=True, comment='是否达成目标: yes, no'),
    sa.Column('deviation', sa.Float(), nullable=True, comment='偏差值（实际值-目标值）'),
    sa.Column('deviation_percentage', sa.Float(), nullable=True, comment='偏差百分比'),
    sa.Column('analysis_notes', sa.Text(), nullable=True, comment='分析说明'),
    sa.Column('improvement_actions', sa.Text(), nullable=True, comment='改进措施'),
    sa.Column('risk_level', sa.String(length=20), nullable=True, comment='风险等级: low, medium, high, critical'),
    sa.Column('year', sa.Integer(), nullable=True, comment='年份'),
    sa.Column('quarter', sa.String(length=10), nullable=True, comment='季度'),
    sa.Column('month', sa.String(length=10), nullable=True, comment='月份'),
    sa.Column('week', sa.Integer(), nullable=True, comment='周数'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='最后更新者'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_target',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_name', sa.String(length=100), nullable=True, comment='目标名称'),
    sa.Column('target_category', sa.String(length=50), nullable=True, comment='目标分类: fault_resolution, availability, proactive_discovery, customer_satisfaction, system_performance'),
    sa.Column('description', sa.Text(), nullable=True, comment='目标描述'),
    sa.Column('target_value', sa.Float(), nullable=True, comment='目标值'),
    sa.Column('unit', sa.String(length=20), nullable=True, comment='单位：分钟、小时、百分比、次数等'),
    sa.Column('target_type', sa.String(length=20), nullable=True, comment='目标类型: minimum(最小值), maximum(最大值), exact(精确值)'),
    sa.Column('effective_date', sa.DateTime(), nullable=True, comment='生效日期'),
    sa.Column('expiry_date', sa.DateTime(), nullable=True, comment='失效日期'),
    sa.Column('year', sa.Integer(), nullable=True, comment='目标年份'),
    sa.Column('quarter', sa.String(length=10), nullable=True, comment='目标季度：Q1, Q2, Q3, Q4 或 ALL'),
    sa.Column('month', sa.String(length=10), nullable=True, comment='目标月份：01-12 或 ALL'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态: active, inactive, archived'),
    sa.Column('priority', sa.String(length=20), nullable=True, comment='优先级: high, medium, low'),
    sa.Column('baseline_value', sa.Float(), nullable=True, comment='基准值'),
    sa.Column('challenge_value', sa.Float(), nullable=True, comment='挑战值'),
    sa.Column('warning_threshold', sa.Float(), nullable=True, comment='预警阈值'),
    sa.Column('critical_threshold', sa.Float(), nullable=True, comment='严重阈值'),
    sa.Column('related_metric', sa.String(length=100), nullable=True, comment='关联的指标项'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='负责部门'),
    sa.Column('responsible_person', sa.String(length=100), nullable=True, comment='负责人'),
    sa.Column('calculation_rule', sa.Text(), nullable=True, comment='计算规则和方式'),
    sa.Column('data_source', sa.String(length=100), nullable=True, comment='数据来源'),
    sa.Column('update_frequency', sa.String(length=50), nullable=True, comment='更新频率: daily, weekly, monthly, quarterly'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注说明'),
    sa.Column('tags', sa.String(length=255), nullable=True, comment='标签，用逗号分隔'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='最后更新者'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance_target')
    op.drop_table('performance_record')
    # ### end Alembic commands ###
